### ISSUE TITLE
Crashes when entering Lon Lon ranch (Adult and Child) on SoH (compiled with GC (not debug) and GC MQ  (not debug)

### ISSUE THREAD

**Issue by Silails** [ROGsamurai/Djipis-Ocarina-of-Time-3DS-Experience#1]
Basically the Title, but it doesn't crash without the NPC Textures pack, I suspect Ingo to be the root of the problem?

Love the textures and models, I would love to be able to either have a fully alt version so that it would be possible to alternate between n64 and 3ds assets

**Comment by ROGsamurai** [comment]
Updating The pack. The basic textures will come first, then I'll add the upscaled versions 1 by 1.
